version: "3.9"
services:
  react-app:
    image: react-docker
    stdin_open: true
    ports: ["3000:3000"]
    networks:
      - mern-app
  node-server:
    image: node-docker
    ports: ["8080:8080"]
    env_file:
      - "server/.env"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
